apiVersion: v1
name: fluent-bit
description: Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
keywords:
  - logging
  - fluent-bit
version: 0.40.0
appVersion: 2.2.0
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/fluentd/fluentbit/icon/fluentbit-icon-color.svg
home: https://fluentbit.io/
sources:
  - https://github.com/fluent/fluent-bit/
maintainers:
  - name: shahenvaz
    email: shahenvaz.khan@nashtechglobals.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated Fluent Bit OCI image to v2.2.0."
